apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: default
      containers:
      - name: backend
        image: gcr.io/e-varejo/backend@sha256:75185d3a5c9e678eda54d857e1542ae33667678df155eb7022095d99990b3814
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: 35.199.117.54
        - name: DB_USER
          value: postgres
        - name: DB_PASS
          value: postgres
        - name: DB_NAME
          value: wikimovie
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: backend-external
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
  - name: http-back
    port: 3000
    targetPort: 3000
---    

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: gcr.io/e-varejo/frontend@sha256:bd37d5b03d766e0e76932fbd6d046a6e5d09cdd4157daff4e47fe48b1acd15ac
          ports:
          - containerPort: 80
          env:
          - name: BACKEND_PORT
            value: "backend:3000"
---

apiVersion: v1
kind: Service
metadata:
  name: frontend-external
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - name: http-front
    port: 80
    targetPort: 80
