apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: default
      containers:
      - name: backend
        image: gcr.io/e-varejo/backend:v0.0.0
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m
      restartPolicy: OnFailure  
---
apiVersion: v1
kind: Service
metadata:
  name: backend-external
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
  - name: http-back
    port: 3000
    targetPort: 3000
---    

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: gcr.io/e-varejo/frontend:v0.0.0
          ports:
          - containerPort: 80
          env:
          - name: BACKEND_PORT
            value: "backend:3000"
---

apiVersion: v1
kind: Service
metadata:
  name: frontend-external
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - name: http-front
    port: 80
    targetPort: 80