apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: default
      containers:
      - name: backend
        image: gcr.io/e-varejo/backend:0.0.1
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: 35.199.117.54
        - name: DB_USER
          value: postgres
        - name: DB_PASS
          value: postgres
        - name: DB_NAME
          value: wikimovie
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: backend-external
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
  - protocol: TCP
    name: http-back
    port: 3000
---    

# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: frontend-deployment
#   labels:
#     app: frontend
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: frontend
#   template:
#     metadata:
#       labels:
#         app: frontend
#     spec:
#       containers:
#         - name: frontend
#           image: gcr.io/e-varejo/frontend@sha256:0
#           ports:
#           - containerPort: 80
#           env:
#           - name: BACKEND_PORT
#             value: "backend:3000"
# ---

# apiVersion: v1
# kind: Service
# metadata:
#   name: frontend-external
# spec:
#   type: LoadBalancer
#   selector:
#     app: frontend
#   ports:
#   - protocol: TCP
#     name: http-front
#     port: 80
