apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: default
      containers:
      - name: backend
        image: gcr.io/e-varejo/backend:latest
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: 35.199.117.54
        - name: DB_USER
          value: postgres
        - name: DB_PASS
          value: postgres
        - name: DB_NAME
          value: wikimovie
---
apiVersion: v1
kind: Service
metadata:
  name: backend-external
spec:
  type: LoadBalancer
  selector:
    app: backend
  ports:
  - protocol: TCP
    name: http-back
    port: 80 #porta que vai ser exposta
    targetPort: 3000 #porta no container        
---    

apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: gcr.io/e-varejo/frontend:latest
          ports:
          - containerPort: 4201
          env:
          - name: BACKEND_PORT
            value: "backend:3000"
---

apiVersion: v1
kind: Service
metadata:
  name: frontend-external
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - protocol: TCP
    name: http-back
    port: 80 #porta que vai ser exposta
    targetPort: 4201 #porta no container    
